
MYSQL_HOST = "localhost"
MYSQL_USER = "root"
MYSQL_PASSWORD = "Jin@htot1205"
MYSQL_DATABASE = "IIS_DB"
SECRET_KEY = "supersecretkey123"


# EMAIL CONFIG
MAIL_SERVER = "smtp.office365.com"
MAIL_PORT = 587
MAIL_USE_TLS = True

MAIL_USERNAME = "iis@virtualahan.com"
MAIL_PASSWORD = "N)551284096127av2026"